[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker build --build-arg REACT_APP_OPENROUTER_API_KEY=$REACT_APP_OPENROUTER_API_KEY --build-arg REACT_APP_APP_NAME=$REACT_APP_APP_NAME --build-arg REACT_APP_APP_VERSION=$REACT_APP_APP_VERSION -t aireader ."
watchPaths = ["src/**", "public/**", "package.json", "package-lock.json", "Dockerfile"]

[deploy]
startCommand = "http-server build -p 3000 --host 0.0.0.0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
INLINE_RUNTIME_CHUNK = "false"
IMAGE_INLINE_SIZE_LIMIT = "0"
CI = "false"
NPM_CONFIG_CACHE = "/tmp/.npm"
NPM_CONFIG_TMP = "/tmp"
