[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "http-server build -p 3000 --host 0.0.0.0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
INLINE_RUNTIME_CHUNK = "false"
IMAGE_INLINE_SIZE_LIMIT = "0"
CI = "false"