[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "serve -s build -l 3000"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
INLINE_RUNTIME_CHUNK = "false"
IMAGE_INLINE_SIZE_LIMIT = "0"
CI = "false"