[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "serve -s build -l ${PORT:-3000}"
# 使用默认的健康检查（TCP端口检查）
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
INLINE_RUNTIME_CHUNK = "false"
IMAGE_INLINE_SIZE_LIMIT = "0"
CI = "false"